"""Merge verified facts from every source into wiki pages and reference files.

Publish policy (fail closed; see README "Verification"):
  1. Evidence: numbers, part numbers, codes and links must be traceable to the source text (grounding.py).
  2. Local verifier: prose claims publish only when the local verifier said "supported"
     (verify.require_local_pass). A procedure is published all-or-nothing: one unverified step withholds
     the whole list, because a missing step is dangerous.
  3. Safety-critical values (torque, brake/steering/suspension/driveline fasteners, fluid specs) additionally
     need >= verify.safety_min_threads agreeing threads, a manufacturer source, or a reviewer's approval.
     Otherwise they go to wiki/pending_verification.md and are NOT in the page body.
  4. A reviewer's (Claude's or a human's) "reject"/"needs_human" always withholds; a human verdict overrides Claude's.
  5. Text copied verbatim from the source is withheld (the wiki must be reworded).
Output is deterministic so git diffs stay small.
"""
from __future__ import annotations

import csv
import json
import re
import sqlite3
from collections import Counter, defaultdict
from dataclasses import dataclass, field
from difflib import SequenceMatcher
from pathlib import Path
from typing import Any

import yaml

from .config import Config
from .schemas import Fact
from .topics import Topic, TopicIndex

GENERATED = "<!-- Generated by `xw export`. Edit the sources or config, not this file; manual edits are overwritten. -->"
_TORQUE = re.compile(r"(ft[\s.\-·]*lbs?|lb[\s.\-·]*ft|in[\s.\-·]*lbs?|n[\s.\-·]*m\b|kgf)", re.I)


@dataclass
class Policy:
    require_local_pass: bool = True
    safety_min_threads: int = 2
    publish_unverified_safety: bool = False

    @classmethod
    def from_cfg(cls, cfg: Config) -> "Policy":
        v = cfg.verify
        return cls(bool(v.require_local_pass), int(v.safety_min_threads), bool(v.publish_unverified_safety))


Verdicts = dict[str, dict[str, str]]  # claim_key -> {by: verdict}


@dataclass
class FactRow:
    id: int
    thread_id: int
    source_id: str
    source_type: str
    trust: int
    url: str
    thread_title: str
    author: str
    posted: str
    fact: Fact
    grounding: dict[str, Any]
    verdicts: Verdicts = field(default_factory=dict)

    @property
    def sid(self) -> str:
        return f"t{self.thread_id}"


def gate(row: FactRow, key: str, policy: Policy) -> tuple[bool, str, str]:
    """(publishable, review_tag, why_withheld). A human verdict decides alone, then Claude's, then the local verifier."""
    v = row.verdicts.get(key, {})
    for by in ("human", "claude"):
        d = v.get(by)
        if d == "approve":
            return True, f"{by.capitalize()}-reviewed", ""
        if d in ("reject", "needs_human"):
            return False, "", f"{by} review: {d}"
    if not policy.require_local_pass:
        return True, "", ""
    local = v.get("local")
    if local == "supported":
        return True, "", ""
    return False, "", f"local verifier: {local or 'not run'}"


def _norm(s: str) -> str:
    return re.sub(r"\W+", " ", s.lower()).strip()


def _norm_value(value: str, unit: str) -> str:
    v = f"{value} {unit}".lower()
    v = re.sub(r"ft[\s.\-·]*lbs?|lb[\s.\-·]*ft", "ftlb", v)
    v = re.sub(r"\bn[\s.\-·]*m\b", "nm", v)
    return re.sub(r"[\s,]+", "", v)


def _dedupe(items: list[tuple[str, str]]) -> list[tuple[str, list[str]]]:
    """items: (text, sid). Near-duplicate texts merge; returns (text, [sids])."""
    kept: list[tuple[str, list[str]]] = []
    for text, sid in items:
        for k, sids in kept:
            if SequenceMatcher(None, _norm(text), _norm(k)).ratio() >= 0.88:
                if sid not in sids:
                    sids.append(sid)
                break
        else:
            kept.append((text.strip(), [sid]))
    return kept


def is_safety(value: str, unit: str, flag: bool) -> bool:
    return flag or bool(_TORQUE.search(f"{value} {unit}"))


def load_rows(conn: sqlite3.Connection) -> list[FactRow]:
    verdicts: dict[int, Verdicts] = defaultdict(lambda: defaultdict(dict))
    for v in conn.execute("SELECT fact_id, claim_key, by, verdict FROM verdicts"):
        verdicts[v["fact_id"]][v["claim_key"]][v["by"]] = v["verdict"]
    q = """SELECT f.id, f.thread_id, f.fact_json, f.grounding_json, t.url, t.title, t.author, t.posted,
                  s.id AS sid, s.type AS stype, s.trust
           FROM facts f JOIN threads t ON t.id=f.thread_id JOIN sources s ON s.id=t.source_id ORDER BY f.id"""
    return [
        FactRow(r["id"], r["thread_id"], r["sid"], r["stype"], r["trust"], r["url"], r["title"], r["author"], r["posted"],
                Fact.model_validate_json(r["fact_json"]), json.loads(r["grounding_json"]),
                {k: dict(v) for k, v in verdicts.get(r["id"], {}).items()})
        for r in conn.execute(q)
    ]


@dataclass
class Page:
    topic: Topic
    rows: list[FactRow] = field(default_factory=list)
    dropped: list[dict[str, str]] = field(default_factory=list)   # withheld items, with the reason
    pending: list[dict[str, str]] = field(default_factory=list)   # safety-critical values awaiting corroboration/review
    disputes: list[str] = field(default_factory=list)
    single_source_safety: list[str] = field(default_factory=list)
    reviewed_items: int = 0


def build_pages(rows: list[FactRow], topics: TopicIndex) -> dict[tuple[str, str], Page]:
    pages: dict[tuple[str, str], Page] = {}
    for row in rows:
        topic = topics.resolve(row.fact.topic, row.fact.category)
        pages.setdefault((topic.category, topic.slug), Page(topic)).rows.append(row)
    return pages


def confidence_for(page: Page) -> str:
    if page.disputes:
        return "disputed"
    if any(r.source_type == "manufacturer" for r in page.rows):
        return "confirmed"
    threads = {r.thread_id for r in page.rows}
    authors = {r.author for r in page.rows if r.author}
    if len(threads) >= 2 and len(authors) >= 2:
        return "community-consensus"
    return "[Unverified]"


def _fmt_src(sids: list[str]) -> str:
    return f" [{', '.join(sids)}]" if sids else ""


def _tagged(text: str, tag: str) -> str:
    return f"{text} ({tag})" if tag else text


def render_page(page: Page, scope_years: tuple[int, int], policy: Policy) -> tuple[str, dict[str, Any]]:
    rows = sorted(page.rows, key=lambda r: (-r.trust, r.id))
    drop = lambda r, kind, text, why: page.dropped.append({"kind": kind, "text": text[:160], "url": r.url, "why": why})  # noqa: E731

    summaries: list[tuple[str, str]] = []
    steps_by_row: list[tuple[FactRow, list[str]]] = []
    symptoms: list[tuple[str, str]] = []
    tips: list[tuple[str, str]] = []
    mistakes: list[tuple[str, str]] = []
    tools: list[tuple[str, str]] = []
    parts: dict[str, dict[str, Any]] = {}
    specs: dict[str, dict[str, Any]] = {}
    diagrams: list[tuple[str, str]] = []

    for r in rows:
        f, g, sid = r.fact, r.grounding, r.sid
        copied = g["copied"]

        if f.summary:
            ok, tag, why = gate(r, "summary", policy)
            if copied["summary"]:
                drop(r, "summary", f.summary, "verbatim overlap with source")
            elif not ok:
                drop(r, "summary", f.summary, why)
            else:
                page.reviewed_items += bool(tag)
                summaries.append((f.summary, sid))

        # procedure: all-or-nothing
        proc_ok = bool(f.steps)
        for i, step in enumerate(f.steps):
            ok, tag, why = gate(r, f"step:{i}", policy)
            if copied["steps"][i] or not ok:
                proc_ok = False
                drop(r, f"step {i + 1} (procedure withheld)", step, "verbatim overlap with source" if copied["steps"][i] else why)
            page.reviewed_items += bool(tag and ok)
        steps_by_row.append((r, list(f.steps) if proc_ok else []))

        for key, lst, flags, dest in (("symptom", f.symptoms, copied["symptoms"], symptoms),
                                      ("tip", f.tips, copied["tips"], tips),
                                      ("mistake", f.mistakes, copied["mistakes"], mistakes)):
            for i, text in enumerate(lst):
                ok, tag, why = gate(r, f"{key}:{i}", policy)
                if flags[i]:
                    drop(r, key, text, "verbatim overlap with source")
                elif not ok:
                    drop(r, key, text, why)
                else:
                    page.reviewed_items += bool(tag)
                    dest.append((text, sid))

        for i, t in enumerate(f.tools):
            ok, tag, why = gate(r, f"tool:{i}", policy)
            if ok:
                tools.append((t, sid))
            else:
                drop(r, "tool", t, why)

        for i, p in enumerate(f.parts):
            if not g["parts"][i]:
                drop(r, "part", f"{p.name} {p.part_number}", "part number/evidence not found in source")
                continue
            ok, tag, why = gate(r, f"part:{i}", policy)
            if not ok:
                drop(r, "part", f"{p.name} {p.part_number}", why)
                continue
            page.reviewed_items += bool(tag)
            key = _norm(p.part_number) or _norm(p.name)
            slot = parts.setdefault(key, {"name": p.name, "part_number": p.part_number, "notes": [], "sids": []})
            if p.notes and p.notes not in slot["notes"]:
                slot["notes"].append(p.notes)
            if sid not in slot["sids"]:
                slot["sids"].append(sid)

        for i, s in enumerate(f.specs):
            label = f"{s.item}: {s.value} {s.unit}".strip()
            if not g["specs"][i]:
                drop(r, "spec", label, "value/evidence not found in source")
                continue
            ok, tag, why = gate(r, f"spec:{i}", policy)
            if not ok:
                drop(r, "spec", label, why)
                continue
            slot = specs.setdefault(_norm(s.item), {"item": s.item, "values": {}, "safety": False})
            v = slot["values"].setdefault(_norm_value(s.value, s.unit), {
                "display": f"{s.value} {s.unit}".strip(), "sids": [], "threads": set(), "reviewed": "", "manufacturer": False, "url": r.url})
            if sid not in v["sids"]:
                v["sids"].append(sid)
            v["threads"].add(r.thread_id)
            v["reviewed"] = v["reviewed"] or tag
            v["manufacturer"] = v["manufacturer"] or r.source_type == "manufacturer"
            slot["safety"] = slot["safety"] or is_safety(s.value, s.unit, s.safety_critical)

        for i, u in enumerate(f.diagram_links):
            if g["diagrams"][i]:
                diagrams.append((u, sid))

    # specs: corroboration, disputes, and the safety-critical gate
    spec_lines: list[str] = []
    for slot in sorted(specs.values(), key=lambda s: s["item"].lower()):
        vals = list(slot["values"].values())
        strict = slot["safety"] and not policy.publish_unverified_safety
        if len(vals) > 1:
            approved = [v for v in vals if v["reviewed"]]
            if len(approved) == 1:
                vals = approved  # a reviewer settled the disagreement
            elif strict:
                page.disputes.append(slot["item"])
                page.pending.append({"item": slot["item"], "value": " vs ".join(v["display"] for v in vals),
                                     "why": "sources disagree", "url": vals[0]["url"]})
                continue
            else:
                page.disputes.append(slot["item"])
                alts = "; ".join(f"{v['display']}{_fmt_src(v['sids'])}" for v in vals)
                spec_lines.append(f"- **{slot['item']}**: DISPUTED, sources disagree: {alts}")
                continue
        v = vals[0]
        n = len(v["threads"])
        if v["reviewed"]:
            tag = v["reviewed"]
        elif v["manufacturer"]:
            tag = "manufacturer source"
        elif n >= 2 and (not strict or n >= policy.safety_min_threads):
            tag = f"community-consensus, {n} threads"
        elif strict and n < policy.safety_min_threads:
            page.pending.append({"item": slot["item"], "value": v["display"], "why": f"only {n} thread(s); needs {policy.safety_min_threads} or a review", "url": v["url"]})
            continue
        else:
            tag = "[Unverified] single report"
            if slot["safety"]:
                page.single_source_safety.append(f"{slot['item']}: {v['display']}")
        page.reviewed_items += bool(v["reviewed"])
        spec_lines.append(f"- **{slot['item']}**: {v['display']}{_fmt_src(v['sids'])} ({tag})")

    proc = [(r, s) for r, s in steps_by_row if s]
    proc.sort(key=lambda rs: (-len(rs[1]), -rs[0].trust, rs[0].id))

    years = sorted({y for r in rows for y in r.fact.years if scope_years[0] <= y <= scope_years[1]})
    diffs = sorted(r.fact.difficulty for r in rows if r.fact.difficulty)
    est = Counter(r.fact.est_time for r in rows if r.fact.est_time).most_common(1)
    conf = confidence_for(page)
    fm = {
        "title": page.topic.title,
        "category": page.topic.category,
        "applies_to": {"years": years, "trims": sorted({t for r in rows for t in r.fact.trims}),
                       "engine": sorted({e for r in rows for e in r.fact.engines}),
                       "drivetrain": sorted({d for r in rows for d in r.fact.drivetrain})},
        "shared_platform": sorted({s for r in rows for s in r.fact.shared_platform}),
        "difficulty": diffs[len(diffs) // 2] if diffs else None,
        "est_time": est[0][0] if est else None,
        "tools": [t for t, _ in _dedupe(tools)],
        "parts": [{"name": p["name"], "oem_part_no": p["part_number"]} for p in sorted(parts.values(), key=lambda p: p["name"].lower())],
        "sources": sorted({r.sid for r in rows}, key=lambda s: int(s[1:])),
        "confidence": conf,
        "verification": {"local_pass_required": policy.require_local_pass, "reviewed_items": page.reviewed_items,
                         "withheld_items": len(page.dropped), "pending_safety_values": len(page.pending)},
    }

    out = [GENERATED, "---", yaml.safe_dump(fm, sort_keys=False, allow_unicode=True).strip(), "---", "", f"# {page.topic.title}", ""]
    if conf == "[Unverified]":
        out += ["> **[Unverified]** This page rests on a single community report. Cross-check before relying on it.", ""]
    if page.single_source_safety:
        out += ["> **Safety-critical values below come from one source only.** Verify against the factory service manual before use.", ""]
    if page.pending:
        out += ["> Some safety-critical values for this topic are withheld until verified. See `pending_verification.md`.", ""]
    out += ["## Summary", ""]
    if summaries:
        for text, sids in _dedupe(summaries):
            out += [f"{text}{_fmt_src(sids)}", ""]
    else:
        out += ["_No verified summary yet._", ""]
    if symptoms:
        out += ["## Symptoms / When you need this", ""] + [f"- {t}{_fmt_src(s)}" for t, s in _dedupe(symptoms)] + [""]
    if proc:
        r0, steps0 = proc[0]
        out += ["## Procedure", ""] + [f"{i}. {s}" for i, s in enumerate(steps0, 1)] + ["", f"_Procedure reported by [{r0.sid}]._", ""]
        for r, s in proc[1:]:
            if SequenceMatcher(None, _norm(" ".join(s)), _norm(" ".join(steps0))).ratio() >= 0.85:
                continue
            out += [f"<details><summary>Alternate procedure [{r.sid}]</summary>", ""] + [f"{i}. {x}" for i, x in enumerate(s, 1)] + ["", "</details>", ""]
    if fm["tools"]:
        out += ["## Tools", ""] + [f"- {t}{_fmt_src(s)}" for t, s in _dedupe(tools)] + [""]
    if parts:
        out += ["## Parts", ""]
        for p in sorted(parts.values(), key=lambda p: p["name"].lower()):
            pn = f" ({p['part_number']})" if p["part_number"] else ""
            note = f": {'; '.join(p['notes'])}" if p["notes"] else ""
            out.append(f"- {p['name']}{pn}{note}{_fmt_src(p['sids'])}")
        out.append("")
    if spec_lines:
        out += ["## Specifications", ""] + spec_lines + [""]
    if tips:
        out += ["## Tips & gotchas", ""] + [f"- {t}{_fmt_src(s)}" for t, s in _dedupe(tips)] + [""]
    if mistakes:
        out += ["## Common mistakes", ""] + [f"- {t}{_fmt_src(s)}" for t, s in _dedupe(mistakes)] + [""]
    if diagrams:
        out += ["## Diagrams (links only)", ""] + [f"- {u} [{s}]" for u, s in sorted(set(diagrams))] + [""]
    out += ["## Source attributions", ""]
    seen: set[int] = set()
    for r in sorted(rows, key=lambda r: r.thread_id):
        if r.thread_id in seen:
            continue
        seen.add(r.thread_id)
        who = f"{r.author}, " if r.author else ""
        when = f", {r.posted[:10]}" if r.posted else ""
        out.append(f"- **{r.sid}**: {who}\"{r.thread_title}\"{when}. {r.url}")
    out.append("")
    return "\n".join(out), {"confidence": conf, "n_threads": len(seen), "years": years}


# ---------------------------------------------------------------------------------------------
def _write(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def _dtc_table(rows: list[FactRow], policy: Policy) -> list[list[str]]:
    by_code: dict[str, list[tuple[FactRow, Any]]] = defaultdict(list)
    for r in rows:
        for i, d in enumerate(r.fact.dtcs):
            if r.grounding["dtcs"][i] and gate(r, f"dtc:{i}", policy)[0]:
                by_code[d.code.strip().upper()].append((r, d))
    table = []
    for code in sorted(by_code):
        items = by_code[code]
        desc = Counter(d.description for _, d in items if d.description).most_common(1)
        causes = Counter(c.strip() for _, d in items for c in d.causes if c.strip())
        tests = [t for t, _ in _dedupe([(t, "") for _, d in items for t in d.tests])]
        fixes = [t for t, _ in _dedupe([(d.fix, "") for _, d in items if d.fix])]
        table.append([code, desc[0][0] if desc else "", " | ".join(c for c, _ in causes.most_common(8)),
                      " | ".join(tests[:6]), " | ".join(fixes[:3]),
                      ",".join(sorted({r.sid for r, _ in items}, key=lambda s: int(s[1:])))])
    return table


def export_all(cfg: Config, conn: sqlite3.Connection, topics: TopicIndex) -> dict[str, Any]:
    wiki = cfg.wiki_dir
    policy = Policy.from_cfg(cfg)
    rows = load_rows(conn)
    pages = build_pages(rows, topics)
    scope = (cfg.scope.years[0], cfg.scope.years[1])

    for cat in topics.category_titles:  # remove stale generated pages
        for old in (wiki / cat).glob("*.md"):
            if old.read_text(encoding="utf-8", errors="ignore").startswith(GENERATED):
                old.unlink()

    summary: dict[str, dict[str, Any]] = {}
    dropped: list[tuple[str, dict[str, str]]] = []
    pending: list[tuple[str, dict[str, str]]] = []
    disputes: list[tuple[str, str]] = []
    single: list[tuple[str, str]] = []
    for (cat, slug), page in sorted(pages.items()):
        text, meta = render_page(page, scope, policy)
        _write(wiki / cat / f"{slug}.md", text + "\n")
        summary[f"{cat}/{slug}"] = {"title": page.topic.title, **meta}
        dropped += [(page.topic.title, d) for d in page.dropped]
        pending += [(page.topic.title, d) for d in page.pending]
        disputes += [(page.topic.title, d) for d in page.disputes]
        single += [(page.topic.title, d) for d in page.single_source_safety]

    idx = [GENERATED, "# Xterra (N50) wiki index", "", "Status: `not-started` means no verified source has contributed yet.", ""]
    for cat, title in topics.category_titles.items():
        idx += [f"## {title}", "", "| Topic | Status | Threads |", "|---|---|---|"]
        for t in sorted((t for t in topics.topics if t.category == cat), key=lambda t: t.title.lower()):
            m = summary.get(f"{cat}/{t.slug}")
            idx.append(f"| [{t.title}]({cat}/{t.slug}.md) | {m['confidence']} | {m['n_threads']} |" if m else f"| {t.title} | not-started | 0 |")
        idx.append("")
    _write(wiki / "index.md", "\n".join(idx))

    dtc = _dtc_table(rows, policy)
    with (wiki / "dtc_table.csv").open("w", newline="", encoding="utf-8") as fh:
        w = csv.writer(fh)
        w.writerow(["code", "description", "likely_causes_ranked", "test_steps", "fix", "source_ids"])
        w.writerows(dtc)

    pd_lines = [GENERATED, "# Parts diagrams (links only)", "",
                "Links point at the original host. Reuse permission is unknown unless stated; do not copy images into the repo.", ""]
    by_topic: dict[str, set[tuple[str, str]]] = defaultdict(set)
    for r in rows:
        for u, ok in zip(r.fact.diagram_links, r.grounding["diagrams"]):
            if ok:
                by_topic[topics.resolve(r.fact.topic, r.fact.category).title].add((u, r.sid))
    for title in sorted(by_topic):
        pd_lines += [f"## {title}", ""] + [f"- {u} [{s}]" for u, s in sorted(by_topic[title])] + [""]
    if not by_topic:
        pd_lines.append("_None found yet._")
    _write(wiki / "parts_diagrams.md", "\n".join(pd_lines) + "\n")

    ic = [GENERATED, "# Xterra / Frontier / Titan interchange", "", "| Topic | Shared with | Years | Threads | Status |", "|---|---|---|---|---|"]
    grouped: dict[str, list[FactRow]] = defaultdict(list)
    for r in rows:
        if r.fact.shared_platform and gate(r, "summary", policy)[0]:
            grouped[topics.resolve(r.fact.topic, r.fact.category).title].append(r)
    for title in sorted(grouped):
        rs = grouped[title]
        n = len({r.thread_id for r in rs})
        status = "confirmed" if any(r.source_type == "manufacturer" for r in rs) else ("community-consensus" if n >= 2 else "unconfirmed")
        ic.append(f"| {title} | {', '.join(sorted({s for r in rs for s in r.fact.shared_platform}))} | "
                  f"{', '.join(str(y) for y in sorted({y for r in rs for y in r.fact.years})) or 'n/a'} | {n} | {status} |")
    _write(wiki / "interchange.md", "\n".join(ic) + "\n")

    src_rows = conn.execute(
        """SELECT t.id, t.source_id, t.url, t.title, t.author, t.posted, t.kind, t.status, s.trust,
                  (SELECT fetched_at FROM fetches f WHERE f.url=t.url) AS scraped
           FROM threads t JOIN sources s ON s.id=t.source_id
           WHERE t.id IN (SELECT DISTINCT thread_id FROM facts) ORDER BY t.id"""
    ).fetchall()
    topics_by_thread: dict[int, set[str]] = defaultdict(set)
    for r in rows:
        topics_by_thread[r.thread_id].add(topics.resolve(r.fact.topic, r.fact.category).title)
    _write(wiki / "sources.json", json.dumps([
        {"id": f"t{r['id']}", "source_id": r["source_id"], "url": r["url"], "thread_title": r["title"],
         "author_handle": r["author"], "date_posted": r["posted"], "date_scraped": r["scraped"], "type": r["kind"],
         "trust_score": r["trust"], "topics": sorted(topics_by_thread[r["id"]]), "status": r["status"]}
        for r in src_rows], indent=2) + "\n")

    pv = [GENERATED, "# Pending verification (NOT published)", "",
          "Safety-critical values that passed the evidence checks but are not yet corroborated. They stay out of the wiki "
          f"until {policy.safety_min_threads}+ independent threads agree, a manufacturer source confirms them, or a reviewer approves them "
          "(`xw review-export`, then the `wiki-reviewer` agent in Claude Code, then `xw review-apply`).", "",
          "| Topic | Item | Value | Why pending | Source |", "|---|---|---|---|---|"]
    pv += [f"| {t} | {d['item']} | {d['value']} | {d['why']} | {d['url']} |" for t, d in pending] or ["| _none_ | | | | |"]
    _write(wiki / "pending_verification.md", "\n".join(pv) + "\n")

    oq = [GENERATED, "# Open questions and gaps", ""]
    blocked = conn.execute("SELECT id, name, reason FROM sources WHERE status='blocked'").fetchall()
    oq += ["## Blocked sources", ""] + ([f"- **{b['id']}** ({b['name']}): {b['reason']}" for b in blocked] or ["_None._"]) + [""]
    bad_threads = conn.execute("SELECT source_id, status, error, COUNT(*) AS n FROM threads WHERE status IN ('skipped','error') GROUP BY 1,2,3").fetchall()
    oq += ["## Threads skipped or failed", ""] + ([f"- {b['source_id']}: {b['n']} thread(s) {b['status']} ({b['error']})" for b in bad_threads] or ["_None._"]) + [""]
    oq += ["## Disputed values", ""] + ([f"- {t}: {d}" for t, d in disputes] or ["_None._"]) + [""]
    oq += ["## Safety-critical values published from one source (verify against the factory service manual)", ""] + ([f"- {t}: {d}" for t, d in single] or ["_None._"]) + [""]
    oq += ["## Items withheld from publication", "",
           "Claims the pipeline refused to publish, with the reason (evidence missing, verifier disagreed, reviewer rejected, copied text).", ""]
    oq += [f"- {t}: {d['kind']}: `{d['text']}`. Reason: {d['why']}. ({d['url']})" for t, d in dropped] or ["_None._"]
    oq += ["", "## Topics with no coverage yet", ""]
    missing = [t for t in topics.topics if f"{t.category}/{t.slug}" not in summary]
    oq += [f"- [{t.category}] {t.title}" for t in missing] or ["_None._"]
    _write(wiki / "open_questions.md", "\n".join(oq) + "\n")

    return {"pages": len(pages), "facts": len(rows), "dtc_codes": len(dtc), "dropped": len(dropped), "pending": len(pending),
            "disputes": len(disputes), "missing_topics": len(missing)}
